const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{Text: 0},
	{Sprite2: 0},
	{kanan: 0},
	{tembak: 0},
	{"8Direction": 0},
	{player: 0},
	{Bullet: 0},
	{laser: 0},
	{Sprite8: 0},
	{enemy: 0},
	{Text2: 0},
	{kiri: 0},
	{Touch: 0},
	{score: 0},
	{live: 0},
	{Sprite: 0},
	{play: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{backgorund: 0},
	{Sprite7: 0},
	{Sprite10: 0},
	{Sprite12: 0},
	{youWin: 0},
	{reply: 0},
	{home: 0},
	{Audio: 0},
	{Particles: 0},
	{Keyboard: 0},
	{Lives: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	kanan: class extends self.ISpriteInstance {},
	tembak: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	laser: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	kiri: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	score: class extends self.ITextInstance {},
	live: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	backgorund: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	youWin: class extends self.ISpriteInstance {},
	reply: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	Keyboard: class extends self.IInstance {}
}